---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

<!-- badges: start -->
<!-- badges: end -->

# colourpickr
A Python package that can be used to extract colours from images for use in data visualization projects.

## Overview

This package allows users to integrate unique colour palettes into their graphs for exploratory data analysis. The colours are retrieved from image data (via URL) and are selected based on their overall prominence in a picture. While there are existing tools that are used to process images and create figures independently, we aim to combine both of their functionalities to help programmers easily design effective and creative visualizations.

## Where Our Package Fits

There does exist similar functions in R that provide similar functionality to our package. packages are capable of colour extraction and data visualization, but none exist that combine the two functions to our knowledge. Some examples of such packages are as follows:

- [Magick](https://docs.ropensci.org/magick/articles/intro.html): This allows you to extract the colours of the image and the quantity of each colour in the image. However, this does not convert this into a colour palette, nor does this package have data visualization capabilities built in.

- [Colorfindr](https://github.com/zumbov2/colorfindr):  This again, allows you to extract the colours of the image and the quantity of each colour in the image. However, this does not convert this into a colour palette, nor does this package have data visualization capabilities built in.

- [paletteR](https://github.com/AndreaCirilloAC/paletter): This package allows you to create a colour palette from an image. However, this image must be saved locally, not from a URL, and requires you to call GGPlot or anothe package to graph.

- [Imgpalr](https://github.com/leonawicz/imgpalr): This package allows you to create ualitative, sequential or divergent color palettes from an image. Again, this function does not have data visualization built in to it.

## Installation

You can install the development version of colourpickr from
[GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("UBC-MDS/colourpickr")
```
